name: Update Keys API

on:
  workflow_dispatch:
  push:
    paths:
      - "keys.json"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Commit and push changes
        run: |
          git config --global user.name "Blessed Sensi API"
          git config --global user.email "no-reply@example.com"
          git add keys.json
          git commit -m "Updated keys" || echo "No changes to commit"
          git push
