name: Update Keys

on:
  repository_dispatch:
    types: [update-keys]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update keys.json
        run: |
          echo "${{ github.event.client_payload.content }}" > keys.json

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add keys.json
          git commit -m "Update keys.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
